//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graphic_music.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isAutoStart {
            get {
                return ((bool)(this["isAutoStart"]));
            }
            set {
                this["isAutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float StandartWidhtSpherePen {
            get {
                return ((float)(this["StandartWidhtSpherePen"]));
            }
            set {
                this["StandartWidhtSpherePen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public float MaxWidthSpherePen {
            get {
                return ((float)(this["MaxWidthSpherePen"]));
            }
            set {
                this["MaxWidthSpherePen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float SpherePosCorrect {
            get {
                return ((float)(this["SpherePosCorrect"]));
            }
            set {
                this["SpherePosCorrect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isClearSphere {
            get {
                return ((bool)(this["isClearSphere"]));
            }
            set {
                this["isClearSphere"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isSetSizeFoVolume {
            get {
                return ((bool)(this["isSetSizeFoVolume"]));
            }
            set {
                this["isSetSizeFoVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int sphereColorJumpVal {
            get {
                return ((int)(this["sphereColorJumpVal"]));
            }
            set {
                this["sphereColorJumpVal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public float SeparatorSetColor {
            get {
                return ((float)(this["SeparatorSetColor"]));
            }
            set {
                this["SeparatorSetColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color BackGColorSphere {
            get {
                return ((global::System.Drawing.Color)(this["BackGColorSphere"]));
            }
            set {
                this["BackGColorSphere"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color staticColorSphere {
            get {
                return ((global::System.Drawing.Color)(this["staticColorSphere"]));
            }
            set {
                this["staticColorSphere"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color BackGColorLines {
            get {
                return ((global::System.Drawing.Color)(this["BackGColorLines"]));
            }
            set {
                this["BackGColorLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float SpeedLines {
            get {
                return ((float)(this["SpeedLines"]));
            }
            set {
                this["SpeedLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color DLColor_volume {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_volume"]));
            }
            set {
                this["DLColor_volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color DLColor_volumeR {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_volumeR"]));
            }
            set {
                this["DLColor_volumeR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 0")]
        public global::System.Drawing.Color DLColor_volumeL {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_volumeL"]));
            }
            set {
                this["DLColor_volumeL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color DLColor_ch1 {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_ch1"]));
            }
            set {
                this["DLColor_ch1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color DLColor_ch2 {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_ch2"]));
            }
            set {
                this["DLColor_ch2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color DLColor_ch3 {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_ch3"]));
            }
            set {
                this["DLColor_ch3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color DLColor_ch4 {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_ch4"]));
            }
            set {
                this["DLColor_ch4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color DLColor_ch5 {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_ch5"]));
            }
            set {
                this["DLColor_ch5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color DLColor_ch6 {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_ch6"]));
            }
            set {
                this["DLColor_ch6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color DLColor_ch7 {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_ch7"]));
            }
            set {
                this["DLColor_ch7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color DLColor_ch8 {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_ch8"]));
            }
            set {
                this["DLColor_ch8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color DLColor_ch9 {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_ch9"]));
            }
            set {
                this["DLColor_ch9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color DLColor_ch10 {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_ch10"]));
            }
            set {
                this["DLColor_ch10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color DLColor_ch11 {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_ch11"]));
            }
            set {
                this["DLColor_ch11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color DLColor_ch12 {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_ch12"]));
            }
            set {
                this["DLColor_ch12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color DLColor_ch13 {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_ch13"]));
            }
            set {
                this["DLColor_ch13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color DLColor_ch14 {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_ch14"]));
            }
            set {
                this["DLColor_ch14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color DLColor_ch15 {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_ch15"]));
            }
            set {
                this["DLColor_ch15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color DLColor_ch16 {
            get {
                return ((global::System.Drawing.Color)(this["DLColor_ch16"]));
            }
            set {
                this["DLColor_ch16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float DLWidth_volume {
            get {
                return ((float)(this["DLWidth_volume"]));
            }
            set {
                this["DLWidth_volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float DLWidth_volumeR {
            get {
                return ((float)(this["DLWidth_volumeR"]));
            }
            set {
                this["DLWidth_volumeR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float DLWidth_volumeL {
            get {
                return ((float)(this["DLWidth_volumeL"]));
            }
            set {
                this["DLWidth_volumeL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DLWidth_ch1 {
            get {
                return ((float)(this["DLWidth_ch1"]));
            }
            set {
                this["DLWidth_ch1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DLWidth_ch2 {
            get {
                return ((float)(this["DLWidth_ch2"]));
            }
            set {
                this["DLWidth_ch2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DLWidth_ch3 {
            get {
                return ((float)(this["DLWidth_ch3"]));
            }
            set {
                this["DLWidth_ch3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DLWidth_ch4 {
            get {
                return ((float)(this["DLWidth_ch4"]));
            }
            set {
                this["DLWidth_ch4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DLWidth_ch5 {
            get {
                return ((float)(this["DLWidth_ch5"]));
            }
            set {
                this["DLWidth_ch5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DLWidth_ch6 {
            get {
                return ((float)(this["DLWidth_ch6"]));
            }
            set {
                this["DLWidth_ch6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DLWidth_ch7 {
            get {
                return ((float)(this["DLWidth_ch7"]));
            }
            set {
                this["DLWidth_ch7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DLWidth_ch8 {
            get {
                return ((float)(this["DLWidth_ch8"]));
            }
            set {
                this["DLWidth_ch8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DLWidth_ch9 {
            get {
                return ((float)(this["DLWidth_ch9"]));
            }
            set {
                this["DLWidth_ch9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DLWidth_ch10 {
            get {
                return ((float)(this["DLWidth_ch10"]));
            }
            set {
                this["DLWidth_ch10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DLWidth_ch11 {
            get {
                return ((float)(this["DLWidth_ch11"]));
            }
            set {
                this["DLWidth_ch11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DLWidth_ch12 {
            get {
                return ((float)(this["DLWidth_ch12"]));
            }
            set {
                this["DLWidth_ch12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DLWidth_ch13 {
            get {
                return ((float)(this["DLWidth_ch13"]));
            }
            set {
                this["DLWidth_ch13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DLWidth_ch14 {
            get {
                return ((float)(this["DLWidth_ch14"]));
            }
            set {
                this["DLWidth_ch14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DLWidth_ch15 {
            get {
                return ((float)(this["DLWidth_ch15"]));
            }
            set {
                this["DLWidth_ch15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DLWidth_ch16 {
            get {
                return ((float)(this["DLWidth_ch16"]));
            }
            set {
                this["DLWidth_ch16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string protocolSerial {
            get {
                return ((string)(this["protocolSerial"]));
            }
            set {
                this["protocolSerial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int SerialSpeed {
            get {
                return ((int)(this["SerialSpeed"]));
            }
            set {
                this["SerialSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int startGrModeIndex {
            get {
                return ((int)(this["startGrModeIndex"]));
            }
            set {
                this["startGrModeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int startGrColorModeIndex {
            get {
                return ((int)(this["startGrColorModeIndex"]));
            }
            set {
                this["startGrColorModeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oldSerialPort {
            get {
                return ((string)(this["oldSerialPort"]));
            }
            set {
                this["oldSerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isAutoStartSerial {
            get {
                return ((bool)(this["isAutoStartSerial"]));
            }
            set {
                this["isAutoStartSerial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string startDeviceName {
            get {
                return ((string)(this["startDeviceName"]));
            }
            set {
                this["startDeviceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isAutoUpdateSerialPortsList {
            get {
                return ((bool)(this["isAutoUpdateSerialPortsList"]));
            }
            set {
                this["isAutoUpdateSerialPortsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int AutoUpdateSerialPortsList_Interval {
            get {
                return ((int)(this["AutoUpdateSerialPortsList_Interval"]));
            }
            set {
                this["AutoUpdateSerialPortsList_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isAutoStartApp {
            get {
                return ((bool)(this["isAutoStartApp"]));
            }
            set {
                this["isAutoStartApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GetVolumeIndex {
            get {
                return ((int)(this["GetVolumeIndex"]));
            }
            set {
                this["GetVolumeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isTestModes {
            get {
                return ((bool)(this["isTestModes"]));
            }
            set {
                this["isTestModes"] = value;
            }
        }
    }
}
